"""End-to-end acceptance test for the podcast MCP tool surface.

This is the v1 acceptance test: one call to `post_podcast_draft_from_markdown`
takes a fixture MP3 + Markdown for body and show notes, creates a podcast
draft, uploads the audio, attaches it via PUT (with last_updated_at
threading), runs prepublish, publishes with send=False (no email goes out
to sandbox subscribers), and deletes the resulting post in a finally
block.

If this passes, the whole MCP surface works end-to-end -- no separate
Api or PodcastPost integration step is needed for the MCP path.

Gated on RUN_INTEGRATION_TESTS=1 and the `integration` marker.
"""

from __future__ import annotations

import asyncio
import os
import time
from pathlib import Path

import pytest
from dotenv import load_dotenv

from substack import Api
from substack_mcp.mcp_server import post_podcast_draft_from_markdown

REPO = Path(__file__).resolve().parents[2]
load_dotenv(REPO / ".env")


pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(
        os.getenv("RUN_INTEGRATION_TESTS") != "1",
        reason="set RUN_INTEGRATION_TESTS=1 to run integration tests",
    ),
]


def _build_cleanup_api() -> Api:
    """Build a plain Api for the post-test cleanup call (delete_draft)."""
    cookies_path = os.getenv("COOKIES_PATH")
    cookies_string = os.getenv("COOKIES_STRING")
    publication_url = os.getenv("PUBLICATION_URL")
    if cookies_path or cookies_string:
        return Api(
            cookies_path=cookies_path,
            cookies_string=cookies_string,
            publication_url=publication_url,
        )
    return Api(
        email=os.getenv("EMAIL"),
        password=os.getenv("PASSWORD"),
        publication_url=publication_url,
    )


def test_mcp_post_podcast_draft_from_markdown_end_to_end(tiny_mp3_path, capsys):
    """One MCP call: MP3 + Markdown -> published podcast on sandbox -> deleted."""
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    title = f"[mcp integration {ts}] post_podcast_draft_from_markdown"
    subtitle = "Auto-generated v1 acceptance test"
    show_notes = (
        "## Show notes\n\n"
        "- Generated by `tests/substack_mcp/test_mcp_podcast_integration.py`\n"
        "- Audio attached via `Api.upload_podcast_audio`\n"
        "- Published with `send=False` so no email goes out\n\n"
        "See [the contract](https://example.com/contract) for the wire details.\n"
    )
    body = (
        "This is the post-page body that ships alongside the episode.\n\n"
        "It should round-trip through `draft_body` and appear on the post page.\n"
    )

    started = time.monotonic()
    result = asyncio.run(
        post_podcast_draft_from_markdown(
            title=title,
            subtitle=subtitle,
            show_notes_markdown=show_notes,
            post_body_markdown=body,
            audio_file_path=str(tiny_mp3_path),
            audience="everyone",
            prepublish=True,
            publish=True,
            send=False,
            share_automatically=False,
        )
    )
    elapsed = time.monotonic() - started

    published_id = result["publish"]["id"]
    try:
        # One-line report regardless of pass/fail.
        print(
            f"\n[mcp-integration] published_id={published_id} "
            f"upload_id={result['upload']['id']} "
            f"upload_state={result['upload']['state']!r} "
            f"is_published={result['publish']['is_published']} "
            f"type={result['publish']['type']!r} "
            f"audio_attached={result['publish']['draft_podcast_upload_id'] == result['upload']['id']} "
            f"prepublish_errors={result['prepublish']['errors']!r} "
            f"flow_elapsed={elapsed:.2f}s"
        )

        # 1. Audio uploaded and transcoded.
        assert result["upload"] is not None
        assert result["upload"]["state"] == "transcoded"
        assert result["upload"]["duration"] > 0

        # 2. Prepublish clean (no client-side guards; server is the validator).
        assert result["prepublish"] == {"errors": [], "suggestions": []}

        # 3. Publish succeeded, podcast type preserved, audio attached.
        assert result["publish"]["is_published"] is True
        assert result["publish"]["type"] == "podcast"
        assert (
            result["publish"]["draft_podcast_upload_id"] == result["upload"]["id"]
        ), "audio reference lost during publish"
        assert result["publish"]["draft_title"] == title

        # 4. The draft key reflects the post-PUT state (audio attached) and
        #    is NOT replaced by the publish response.
        assert result["draft"]["draft_podcast_upload_id"] == result["upload"]["id"]

        # 5. No tags were requested.
        assert result["tags"] is None
    finally:
        # Cleanup outside the MCP surface -- delete_draft is not (currently)
        # exposed as an MCP tool.
        api = _build_cleanup_api()
        api.delete_draft(published_id)
