"""
Example: Publishing a podcast episode end-to-end

Demonstrates the full podcast flow:
    1. Build a PodcastPost with title, subtitle, body, show notes
    2. Create the podcast draft on Substack
    3. Upload the MP3 (init -> S3 PUT -> transcode -> poll-until-ready)
    4. Attach the uploaded audio to the draft
    5. Prepublish (server-side validation)
    6. (Optional) Publish the episode

Run without --publish to leave the result as a draft; add --publish to
actually go live. Use --no-send with --publish to publish without firing
the subscriber-email notification.
"""

import argparse
import os
from pathlib import Path

from dotenv import load_dotenv

from substack import Api, PodcastPost

load_dotenv()

DEFAULT_BODY_MD = (
    "This episode was created with the python-substack `publish_podcast.py` example.\n"
)
DEFAULT_SHOW_NOTES_MD = (
    "## Show notes\n\n"
    "- Generated by `examples/publish_podcast.py`\n"
    "- Edit this script to set your own title, body, and show notes.\n"
)


def _read_or_default(path: str | None, default: str) -> str:
    """Return file contents at `path`, or `default` when `path` is None."""
    if path is None:
        return default
    return Path(path).read_text(encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Create, optionally publish, a Substack podcast episode.",
    )
    parser.add_argument(
        "-a",
        "--audio",
        required=True,
        type=str,
        help="Path to the episode MP3 file.",
    )
    parser.add_argument(
        "-t",
        "--title",
        default="Test episode",
        type=str,
        help="Episode title (default: 'Test episode').",
    )
    parser.add_argument(
        "--subtitle",
        default="Created with python-substack",
        type=str,
        help="Episode subtitle.",
    )
    parser.add_argument(
        "--body-file",
        default=None,
        type=str,
        help="Path to a Markdown file for the post-page body. "
             "If omitted, a short default is used.",
    )
    parser.add_argument(
        "--show-notes-file",
        default=None,
        type=str,
        help="Path to a Markdown file for the show notes (podcast_description). "
             "If omitted, a short default is used.",
    )
    parser.add_argument(
        "--audience",
        default="everyone",
        choices=["everyone", "only_paid", "founding", "only_free"],
        help="Audience for the episode (default: everyone).",
    )
    parser.add_argument(
        "--publish",
        help="Publish the episode. Without this flag the script stops at the draft stage.",
        action="store_true",
        default=False,
    )
    parser.add_argument(
        "--no-send",
        help="When combined with --publish, do not email subscribers. "
             "Recommended for sandbox testing.",
        action="store_true",
        default=False,
    )
    parser.add_argument(
        "--cookies",
        help="Path to cookies JSON file for authentication "
             "(optional, can also be set via COOKIES_PATH or COOKIES_STRING env vars).",
        type=str,
        default=None,
    )
    args = parser.parse_args()

    cookies_path = args.cookies or os.getenv("COOKIES_PATH")
    cookies_string = os.getenv("COOKIES_STRING")

    api = Api(
        email=os.getenv("EMAIL") if not cookies_path and not cookies_string else None,
        password=os.getenv("PASSWORD")
        if not cookies_path and not cookies_string
        else None,
        cookies_path=cookies_path,
        cookies_string=cookies_string,
        publication_url=os.getenv("PUBLICATION_URL"),
    )

    user_id = api.get_user_id()

    body_markdown = _read_or_default(args.body_file, DEFAULT_BODY_MD)
    show_notes_markdown = _read_or_default(args.show_notes_file, DEFAULT_SHOW_NOTES_MD)

    # 1. Build the podcast draft in memory.
    pod = (
        PodcastPost(
            title=args.title,
            subtitle=args.subtitle,
            user_id=user_id,
            audience=args.audience,
        )
        .set_body_from_markdown(body_markdown, api=api)
        .set_show_notes_from_markdown(show_notes_markdown, api=api)
    )

    # 2. Create the podcast draft. We need a draft id before we can upload
    #    audio (Substack scopes the upload to a post_id at init time).
    print("Creating draft...")
    draft = api.post_draft(pod.get_draft())
    draft_id = draft["id"]
    print(f"Draft created: id={draft_id}")

    # 3. Upload the audio. This handles init + S3 PUT + transcode + polling
    #    in one call; returns once the media object reports state="transcoded".
    print(f"Uploading audio from {args.audio} ...")
    media = api.upload_podcast_audio(file_path=args.audio, draft_id=draft_id)
    upload_id = media["id"]
    duration_seconds = media["duration"]
    print(
        f"Audio uploaded and transcoded: upload_id={upload_id} "
        f"duration={duration_seconds:.2f}s"
    )

    # 4. Attach the audio to the draft. Thread last_updated_at from the
    #    create response so subsequent PUTs match the server's optimistic
    #    concurrency token (see docs/PODCAST_ARCHITECTURE.md section 7).
    pod.set_audio(upload_id, duration_seconds=duration_seconds)
    pod.last_updated_at = draft.get("draft_updated_at")

    print("Attaching audio to draft...")
    updated = api.put_draft(draft_id, **pod.get_draft())
    print(f"Audio attached: draft_podcast_upload_id={updated['draft_podcast_upload_id']}")

    if not args.publish:
        print(
            f"\nDraft ready (not published). View / edit in the Substack editor, "
            f"or re-run with --publish to publish."
        )
        print(f"Draft id: {draft_id}")
        raise SystemExit(0)

    # 5. Prepublish: server-side validation. Surfaces missing required fields
    #    before we commit to publishing.
    print("\nRunning prepublish validation...")
    prepublish = api.prepublish_draft(draft_id)
    if prepublish.get("errors"):
        print(f"Prepublish FAILED: {prepublish['errors']}")
        raise SystemExit(1)
    if prepublish.get("suggestions"):
        print(f"Prepublish suggestions: {prepublish['suggestions']}")

    # 6. Publish.
    send = not args.no_send
    print(f"Publishing episode (send={send})...")
    published = api.publish_draft(
        draft_id, send=send, share_automatically=False
    )
    print(
        f"Published: id={published['id']} is_published={published['is_published']} "
        f"slug={published.get('slug')!r}"
    )
