"""Integration test for the full podcast publish flow.

End-to-end exercise against a real Substack sandbox:

    1. Build a complete PodcastPost (title, subtitle, body markdown,
       show notes markdown)
    2. POST /drafts to create the podcast shell
    3. Upload a tiny fixture MP3 via Api.upload_podcast_audio
    4. PUT /drafts to attach the audio with last_updated_at threading
    5. GET /drafts/{id}/prepublish, assert errors == []
    6. POST /drafts/{id}/publish with send=False (no email goes out)
    7. Assert is_published == True, type == "podcast",
       draft_podcast_upload_id preserved
    8. Delete the published post in a finally block

Gated on RUN_INTEGRATION_TESTS=1 + the `integration` marker.

`send=False` is critical: this test publishes against the real sandbox,
and email delivery is permanent. Even a zero-subscriber sandbox shouldn't
fire delivery side-effects from CI.
"""

from __future__ import annotations

import os
import time
from pathlib import Path

import pytest
from dotenv import load_dotenv

from substack import Api, PodcastPost

REPO = Path(__file__).resolve().parents[2]
load_dotenv(REPO / ".env")


pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(
        os.getenv("RUN_INTEGRATION_TESTS") != "1",
        reason="set RUN_INTEGRATION_TESTS=1 to run integration tests",
    ),
]


def _build_api() -> Api:
    """Construct an Api client from .env credentials, preferring cookies."""
    cookies_path = os.getenv("COOKIES_PATH")
    cookies_string = os.getenv("COOKIES_STRING")
    publication_url = os.getenv("PUBLICATION_URL")
    if cookies_path or cookies_string:
        return Api(
            cookies_path=cookies_path,
            cookies_string=cookies_string,
            publication_url=publication_url,
        )
    return Api(
        email=os.getenv("EMAIL"),
        password=os.getenv("PASSWORD"),
        publication_url=publication_url,
    )


def test_full_podcast_publish_flow(tiny_mp3_path, capsys):
    """Create -> upload -> attach -> prepublish -> publish(send=False) -> delete."""
    api = _build_api()
    user_id = api.get_user_id()

    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    title = f"[integration test {ts}] full podcast publish flow"
    subtitle = "Auto-generated by tests/substack/test_podcast_publish_integration.py"
    body_markdown = (
        "This is the post-page body of an automatically-published episode. "
        "Safe to delete.\n"
    )
    show_notes_markdown = (
        "## Show notes\n\n"
        "- Generated by the python-substack integration suite\n"
        "- send=False so no email goes out\n"
    )

    pod = (
        PodcastPost(
            title=title,
            subtitle=subtitle,
            user_id=user_id,
            audience="everyone",
            write_comment_permissions="everyone",
        )
        .set_body_from_markdown(body_markdown)
        .set_show_notes_from_markdown(show_notes_markdown)
    )

    flow_started = time.monotonic()
    created = api.post_draft(pod.get_draft())
    draft_id = created["id"]
    create_updated_at = created.get("draft_updated_at")

    try:
        assert created["type"] == "podcast"

        # Upload audio + attach.
        media = api.upload_podcast_audio(
            file_path=str(tiny_mp3_path),
            draft_id=draft_id,
            poll_timeout_seconds=120,
            poll_interval_seconds=2,
        )
        upload_id = media["id"]
        duration_seconds = media["duration"]
        assert media["state"] == "transcoded"

        pod.set_audio(upload_id, duration_seconds=duration_seconds)
        pod.last_updated_at = create_updated_at
        updated = api.put_draft(draft_id, **pod.get_draft())
        assert updated["draft_podcast_upload_id"] == upload_id

        # Prepublish validation.
        prepublish = api.prepublish_draft(draft_id)
        assert prepublish.get("errors") == [], (
            f"prepublish reported errors that should have been caught earlier: "
            f"{prepublish.get('errors')!r}"
        )

        # Publish with send=False so no email goes out from the sandbox.
        published = api.publish_draft(draft_id, send=False, share_automatically=False)
        flow_elapsed = time.monotonic() - flow_started

        print(
            f"\n[integration] draft_id={draft_id} upload_id={upload_id} "
            f"published_id={published.get('id')} "
            f"is_published={published.get('is_published')} "
            f"type={published.get('type')!r} "
            f"audio_attached={published.get('draft_podcast_upload_id') == upload_id} "
            f"prepublish_errors={prepublish.get('errors')!r} "
            f"prepublish_suggestions={prepublish.get('suggestions')!r} "
            f"flow_elapsed={flow_elapsed:.2f}s"
        )

        assert published["is_published"] is True
        assert published["type"] == "podcast"
        assert published["draft_podcast_upload_id"] == upload_id, (
            "audio reference lost during publish"
        )
        assert published["draft_title"] == title
        # publish response uses the same draft id; publish does not re-id.
        assert published["id"] == draft_id
    finally:
        api.delete_draft(draft_id)
