"""Integration test for PodcastPost draft creation + audio attachment.

Exercises the Phase D flow end-to-end against a real Substack sandbox:

    1. Build PodcastPost with body + show notes from Markdown
    2. POST /drafts to create the podcast shell, capture draft_updated_at
    3. Upload a tiny fixture MP3 (reuses Phase C: Api.upload_podcast_audio)
    4. set_audio + thread last_updated_at from the create response
    5. PUT /drafts with the updated payload
    6. Verify the API echoes back title / subtitle / audio UUID / both
       ProseMirror docs, AND that draft_updated_at advanced from the
       create-response value (proof last_updated_at threading is round
       tripping, not just satisfying mock assertions)
    7. Delete the draft in a finally block

No publish call -- that's Phase E.

Gated on RUN_INTEGRATION_TESTS=1 and the `integration` marker.
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path

import pytest
from dotenv import load_dotenv

from substack import Api, PodcastPost

REPO = Path(__file__).resolve().parents[2]
load_dotenv(REPO / ".env")


pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(
        os.getenv("RUN_INTEGRATION_TESTS") != "1",
        reason="set RUN_INTEGRATION_TESTS=1 to run integration tests",
    ),
]


def _build_api() -> Api:
    """Construct an Api client from .env credentials, preferring cookies."""
    cookies_path = os.getenv("COOKIES_PATH")
    cookies_string = os.getenv("COOKIES_STRING")
    publication_url = os.getenv("PUBLICATION_URL")
    if cookies_path or cookies_string:
        return Api(
            cookies_path=cookies_path,
            cookies_string=cookies_string,
            publication_url=publication_url,
        )
    return Api(
        email=os.getenv("EMAIL"),
        password=os.getenv("PASSWORD"),
        publication_url=publication_url,
    )


def test_podcast_draft_create_and_attach_audio(tiny_mp3_path, capsys):
    """Round-trip PodcastPost -> create -> upload audio -> PUT -> verify echo."""
    api = _build_api()
    user_id = api.get_user_id()

    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    title = f"[integration test {ts}] PodcastPost round trip"
    subtitle = "Auto-generated by tests/substack/test_podcast_draft_integration.py"
    body_markdown = (
        "This is the **post-page body** of the episode. "
        "It should round-trip through `draft_body`.\n"
    )
    show_notes_markdown = (
        "## Show notes\n\n"
        "- Topic one\n"
        "- Topic two\n\n"
        "See [example](https://example.com) for more.\n"
    )

    pod = (
        PodcastPost(
            title=title,
            subtitle=subtitle,
            user_id=user_id,
            audience="everyone",
            write_comment_permissions="everyone",
        )
        .set_body_from_markdown(body_markdown)
        .set_show_notes_from_markdown(show_notes_markdown)
    )

    # Step 1: create the podcast draft shell.
    created = api.post_draft(pod.get_draft())
    draft_id = created["id"]
    create_updated_at = created.get("draft_updated_at")

    try:
        assert created["type"] == "podcast", (
            f"expected type=podcast, got {created.get('type')!r}"
        )
        assert created["draft_title"] == title
        assert create_updated_at is not None, (
            "create response missing draft_updated_at -- "
            "cannot exercise last_updated_at threading"
        )

        # Step 2: upload audio (reuses Phase C).
        upload_started = time.monotonic()
        media = api.upload_podcast_audio(
            file_path=str(tiny_mp3_path),
            draft_id=draft_id,
            poll_timeout_seconds=120,
            poll_interval_seconds=2,
        )
        upload_elapsed = time.monotonic() - upload_started
        upload_id = media["id"]
        duration_seconds = media["duration"]
        assert media["state"] == "transcoded"

        # Step 3: attach audio and thread last_updated_at into the PUT payload.
        pod.set_audio(upload_id, duration_seconds=duration_seconds)
        pod.last_updated_at = create_updated_at

        # Step 4: PUT the updated draft.
        updated = api.put_draft(draft_id, **pod.get_draft())
        put_updated_at = updated.get("draft_updated_at")

        # Surface a one-line report for debugging regardless of pass/fail.
        print(
            f"\n[integration] draft_id={draft_id} upload_id={upload_id} "
            f"audio_duration={duration_seconds} "
            f"upload_elapsed={upload_elapsed:.2f}s "
            f"create_updated_at={create_updated_at!r} "
            f"put_updated_at={put_updated_at!r}"
        )

        # Step 5: verify echoes.
        assert updated["type"] == "podcast"
        assert updated["draft_title"] == title
        assert updated["draft_subtitle"] == subtitle
        assert updated["draft_podcast_upload_id"] == upload_id, (
            "Substack did not store the audio UUID -- attachment failed"
        )

        # Body and show notes come back as JSON-stringified ProseMirror docs.
        body_doc = json.loads(updated["draft_body"])
        assert "post-page body" in json.dumps(body_doc), (
            f"body text missing from echoed draft_body: {body_doc!r}"
        )

        desc = updated.get("podcast_description")
        assert desc, "podcast_description was empty/missing in PUT response"
        desc_doc = json.loads(desc)
        assert "Show notes" in json.dumps(desc_doc), (
            f"show notes heading missing from echoed podcast_description: {desc_doc!r}"
        )
        assert "Topic one" in json.dumps(desc_doc)

        # Proof that last_updated_at threading actually round-trips: the
        # server's timestamp advanced after our PUT.
        assert put_updated_at is not None
        assert put_updated_at != create_updated_at, (
            f"draft_updated_at did not advance after PUT "
            f"({create_updated_at!r} -> {put_updated_at!r}); "
            "last_updated_at threading may be a no-op"
        )
    finally:
        api.delete_draft(draft_id)
